package mdn.mdn_recipes.domain.model;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;
import mdn.mdn_recipes.shared.util.UUIDv7;

import java.util.UUID;

@Getter
@Entity
public class Step {

    @Id
    private UUID id;

    @Setter
    @ManyToOne
    @JoinColumn(name = "recipe_id", nullable = false)
    private Recipe recipe;

    @Column(nullable = false)
    private final String description;

    @Column(name = "step_order", nullable = false)
    private final Integer stepOrder;

    public Step(Recipe recipe, String description, Integer stepOrder) {
        this.recipe = recipe;
        this.description = description;
        this.stepOrder = stepOrder;
    }

    // Pre-persist the ID as a UUID v7 generated by the code to ensure DB compatibility
    @PrePersist
    public void prePersist() {
        if (this.id == null)
            this.id = UUIDv7.create();
    }

}
