package mdn.mdn_recipes.entity;

import jakarta.persistence.*;
import lombok.*;
import mdn.mdn_recipes.service.util.UUIDv7;

import java.time.*;
import java.util.*;

@Getter
@Entity
public class Recipe {

    @Id
    private UUID id;

    @Column(nullable = false)
    private String name;

    @Column(columnDefinition = "TEXT")
    private String description;

    @Column(nullable = false)
    private Integer servings;

    @Column(name = "preparation_time", nullable = false)
    private LocalTime preparationTime;

    @Column(name = "image_path", columnDefinition = "TEXT", nullable = false)
    private String imagePath;

    @Column(name = "created_at")
    private final LocalDateTime createdAt = LocalDateTime.now();

    @OneToMany(mappedBy = "recipe", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<Ingredient> ingredients;

    @OneToMany(mappedBy = "recipe", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<Step> steps;

    // Pre-persist the ID as a UUID v7 generated by the code to ensure DB compatibility
    @PrePersist
    public void prePersist() {
        if (this.id == null)
            this.id = UUIDv7.create();
    }

}
