package mdn.mdn_recipes.entity;

import jakarta.persistence.*;
import lombok.Getter;
import mdn.mdn_recipes.service.util.UUIDv7;

import java.util.UUID;

@Getter
@Entity
public class Step {

    @Id
    private UUID id;

    @ManyToOne
    @JoinColumn(name = "recipe_id", nullable = false)
    private Recipe recipe;

    @Column(nullable = false)
    private String description;

    @Column(nullable = false)
    private Integer step_order;

    // Pre-persist the ID as a UUID v7 generated by the code to ensure DB compatibility
    @PrePersist
    public void prePersist() {
        if (this.id == null)
            this.id = UUIDv7.create();
    }

}
